language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="mirage-bootvar-xen"
  matrix:
  - DISTRO=alpine OCAML_VERSION=4.04.2
  - DISTRO=alpine OCAML_VERSION=4.05.0
